// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package com.server.graph_db.grpc.database;

public final class Database {
  private Database() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emptyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatabaseName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatabaseName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016database.proto\032\033google/protobuf/empty." +
      "proto\032\027google/rpc/status.proto\"+\n\005reply\022" +
      "\"\n\006status\030\001 \001(\0132\022.google.rpc.Status\"\017\n\re" +
      "mptyResponse\"\034\n\014DatabaseName\022\014\n\004name\030\001 \001" +
      "(\t2\336\002\n\025databaseConfigService\022)\n\016createDa" +
      "tabase\022\r.DatabaseName\032\006.reply\"\000\0225\n\022getCu" +
      "rrentDatabase\022\016.emptyResponse\032\r.Database" +
      "Name\"\000\022)\n\016deleteDatabase\022\r.DatabaseName\032" +
      "\006.reply\"\000\022\'\n\014dropDatabase\022\r.DatabaseName" +
      "\032\006.reply\"\000\022)\n\016switchDatabase\022\r.DatabaseN" +
      "ame\032\006.reply\"\000\0223\n\027switchToDefaultDatabase" +
      "\022\016.emptyResponse\032\006.reply\"\000\022/\n\023dropDefaul" +
      "tDatabase\022\016.emptyResponse\032\006.reply\"\000B%\n!c" +
      "om.server.graph_db.grpc.databaseP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_reply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reply_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_emptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_emptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emptyResponse_descriptor,
        new java.lang.String[] { });
    internal_static_DatabaseName_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DatabaseName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatabaseName_descriptor,
        new java.lang.String[] { "Name", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
