// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package com.server.graph_db.grpc.database;

public interface replyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.rpc.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.google.rpc.Status status = 1;</code>
   * @return The status.
   */
  com.google.rpc.Status getStatus();
  /**
   * <code>.google.rpc.Status status = 1;</code>
   */
  com.google.rpc.StatusOrBuilder getStatusOrBuilder();
}
