// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

public interface edgeIdsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:edgeIds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .edgeId edgeIds = 1;</code>
   */
  java.util.List<com.server.graph_db.grpc.traverser.edgeId> 
      getEdgeIdsList();
  /**
   * <code>repeated .edgeId edgeIds = 1;</code>
   */
  com.server.graph_db.grpc.traverser.edgeId getEdgeIds(int index);
  /**
   * <code>repeated .edgeId edgeIds = 1;</code>
   */
  int getEdgeIdsCount();
  /**
   * <code>repeated .edgeId edgeIds = 1;</code>
   */
  java.util.List<? extends com.server.graph_db.grpc.traverser.edgeIdOrBuilder> 
      getEdgeIdsOrBuilderList();
  /**
   * <code>repeated .edgeId edgeIds = 1;</code>
   */
  com.server.graph_db.grpc.traverser.edgeIdOrBuilder getEdgeIdsOrBuilder(
      int index);
}
