// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

public interface filterEdgesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filterEdgesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string verticesIds = 1;</code>
   * @return A list containing the verticesIds.
   */
  java.util.List<java.lang.String>
      getVerticesIdsList();
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @return The count of verticesIds.
   */
  int getVerticesIdsCount();
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @param index The index of the element to return.
   * @return The verticesIds at the given index.
   */
  java.lang.String getVerticesIds(int index);
  /**
   * <code>repeated string verticesIds = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the verticesIds at the given index.
   */
  com.google.protobuf.ByteString
      getVerticesIdsBytes(int index);

  /**
   * <code>string edgeLabel = 2;</code>
   * @return The edgeLabel.
   */
  java.lang.String getEdgeLabel();
  /**
   * <code>string edgeLabel = 2;</code>
   * @return The bytes for edgeLabel.
   */
  com.google.protobuf.ByteString
      getEdgeLabelBytes();

  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  java.util.List<com.server.graph_db.grpc.traverser.selectOperator> 
      getSelectOperatorsList();
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  com.server.graph_db.grpc.traverser.selectOperator getSelectOperators(int index);
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  int getSelectOperatorsCount();
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  java.util.List<? extends com.server.graph_db.grpc.traverser.selectOperatorOrBuilder> 
      getSelectOperatorsOrBuilderList();
  /**
   * <code>repeated .selectOperator selectOperators = 3;</code>
   */
  com.server.graph_db.grpc.traverser.selectOperatorOrBuilder getSelectOperatorsOrBuilder(
      int index);
}
