// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traverser.proto

package com.server.graph_db.grpc.traverser;

public interface selectOperatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:selectOperator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fieldName = 1;</code>
   * @return The fieldName.
   */
  java.lang.String getFieldName();
  /**
   * <code>string fieldName = 1;</code>
   * @return The bytes for fieldName.
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <code>string operator = 2;</code>
   * @return The operator.
   */
  java.lang.String getOperator();
  /**
   * <code>string operator = 2;</code>
   * @return The bytes for operator.
   */
  com.google.protobuf.ByteString
      getOperatorBytes();

  /**
   * <code>string fieldValue = 3;</code>
   * @return The fieldValue.
   */
  java.lang.String getFieldValue();
  /**
   * <code>string fieldValue = 3;</code>
   * @return The bytes for fieldValue.
   */
  com.google.protobuf.ByteString
      getFieldValueBytes();
}
