// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package com.server.graph_db.grpc.index;

public interface deleteIndexResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteIndexResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
