// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package com.server.graph_db.grpc.index;

/**
 * Protobuf type {@code deleteIndicesRequest}
 */
public final class deleteIndicesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deleteIndicesRequest)
    deleteIndicesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use deleteIndicesRequest.newBuilder() to construct.
  private deleteIndicesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private deleteIndicesRequest() {
    indicesNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new deleteIndicesRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private deleteIndicesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              indicesNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            indicesNames_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        indicesNames_ = indicesNames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.server.graph_db.grpc.index.Index.internal_static_deleteIndicesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.server.graph_db.grpc.index.Index.internal_static_deleteIndicesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.server.graph_db.grpc.index.deleteIndicesRequest.class, com.server.graph_db.grpc.index.deleteIndicesRequest.Builder.class);
  }

  public static final int INDICESNAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList indicesNames_;
  /**
   * <code>repeated string indicesNames = 1;</code>
   * @return A list containing the indicesNames.
   */
  public com.google.protobuf.ProtocolStringList
      getIndicesNamesList() {
    return indicesNames_;
  }
  /**
   * <code>repeated string indicesNames = 1;</code>
   * @return The count of indicesNames.
   */
  public int getIndicesNamesCount() {
    return indicesNames_.size();
  }
  /**
   * <code>repeated string indicesNames = 1;</code>
   * @param index The index of the element to return.
   * @return The indicesNames at the given index.
   */
  public java.lang.String getIndicesNames(int index) {
    return indicesNames_.get(index);
  }
  /**
   * <code>repeated string indicesNames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the indicesNames at the given index.
   */
  public com.google.protobuf.ByteString
      getIndicesNamesBytes(int index) {
    return indicesNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < indicesNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, indicesNames_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < indicesNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(indicesNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIndicesNamesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.server.graph_db.grpc.index.deleteIndicesRequest)) {
      return super.equals(obj);
    }
    com.server.graph_db.grpc.index.deleteIndicesRequest other = (com.server.graph_db.grpc.index.deleteIndicesRequest) obj;

    if (!getIndicesNamesList()
        .equals(other.getIndicesNamesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIndicesNamesCount() > 0) {
      hash = (37 * hash) + INDICESNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getIndicesNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.index.deleteIndicesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.server.graph_db.grpc.index.deleteIndicesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code deleteIndicesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deleteIndicesRequest)
      com.server.graph_db.grpc.index.deleteIndicesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.graph_db.grpc.index.Index.internal_static_deleteIndicesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.graph_db.grpc.index.Index.internal_static_deleteIndicesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.graph_db.grpc.index.deleteIndicesRequest.class, com.server.graph_db.grpc.index.deleteIndicesRequest.Builder.class);
    }

    // Construct using com.server.graph_db.grpc.index.deleteIndicesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      indicesNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.server.graph_db.grpc.index.Index.internal_static_deleteIndicesRequest_descriptor;
    }

    @java.lang.Override
    public com.server.graph_db.grpc.index.deleteIndicesRequest getDefaultInstanceForType() {
      return com.server.graph_db.grpc.index.deleteIndicesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.server.graph_db.grpc.index.deleteIndicesRequest build() {
      com.server.graph_db.grpc.index.deleteIndicesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.server.graph_db.grpc.index.deleteIndicesRequest buildPartial() {
      com.server.graph_db.grpc.index.deleteIndicesRequest result = new com.server.graph_db.grpc.index.deleteIndicesRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        indicesNames_ = indicesNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.indicesNames_ = indicesNames_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.server.graph_db.grpc.index.deleteIndicesRequest) {
        return mergeFrom((com.server.graph_db.grpc.index.deleteIndicesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.server.graph_db.grpc.index.deleteIndicesRequest other) {
      if (other == com.server.graph_db.grpc.index.deleteIndicesRequest.getDefaultInstance()) return this;
      if (!other.indicesNames_.isEmpty()) {
        if (indicesNames_.isEmpty()) {
          indicesNames_ = other.indicesNames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIndicesNamesIsMutable();
          indicesNames_.addAll(other.indicesNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.server.graph_db.grpc.index.deleteIndicesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.server.graph_db.grpc.index.deleteIndicesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList indicesNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIndicesNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        indicesNames_ = new com.google.protobuf.LazyStringArrayList(indicesNames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @return A list containing the indicesNames.
     */
    public com.google.protobuf.ProtocolStringList
        getIndicesNamesList() {
      return indicesNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @return The count of indicesNames.
     */
    public int getIndicesNamesCount() {
      return indicesNames_.size();
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @param index The index of the element to return.
     * @return The indicesNames at the given index.
     */
    public java.lang.String getIndicesNames(int index) {
      return indicesNames_.get(index);
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the indicesNames at the given index.
     */
    public com.google.protobuf.ByteString
        getIndicesNamesBytes(int index) {
      return indicesNames_.getByteString(index);
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @param index The index to set the value at.
     * @param value The indicesNames to set.
     * @return This builder for chaining.
     */
    public Builder setIndicesNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIndicesNamesIsMutable();
      indicesNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @param value The indicesNames to add.
     * @return This builder for chaining.
     */
    public Builder addIndicesNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIndicesNamesIsMutable();
      indicesNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @param values The indicesNames to add.
     * @return This builder for chaining.
     */
    public Builder addAllIndicesNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureIndicesNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, indicesNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndicesNames() {
      indicesNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indicesNames = 1;</code>
     * @param value The bytes of the indicesNames to add.
     * @return This builder for chaining.
     */
    public Builder addIndicesNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIndicesNamesIsMutable();
      indicesNames_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deleteIndicesRequest)
  }

  // @@protoc_insertion_point(class_scope:deleteIndicesRequest)
  private static final com.server.graph_db.grpc.index.deleteIndicesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.server.graph_db.grpc.index.deleteIndicesRequest();
  }

  public static com.server.graph_db.grpc.index.deleteIndicesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<deleteIndicesRequest>
      PARSER = new com.google.protobuf.AbstractParser<deleteIndicesRequest>() {
    @java.lang.Override
    public deleteIndicesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new deleteIndicesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<deleteIndicesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<deleteIndicesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.server.graph_db.grpc.index.deleteIndicesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

