// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package com.server.graph_db.grpc.index;

public interface deleteIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string indexName = 1;</code>
   * @return The indexName.
   */
  java.lang.String getIndexName();
  /**
   * <code>string indexName = 1;</code>
   * @return The bytes for indexName.
   */
  com.google.protobuf.ByteString
      getIndexNameBytes();
}
