// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface createVertexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:createVertexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  java.util.List<com.server.graph_db.grpc.vertex.edge> 
      getOutgoingEdgesList();
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  com.server.graph_db.grpc.vertex.edge getOutgoingEdges(int index);
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  int getOutgoingEdgesCount();
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  java.util.List<? extends com.server.graph_db.grpc.vertex.edgeOrBuilder> 
      getOutgoingEdgesOrBuilderList();
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  com.server.graph_db.grpc.vertex.edgeOrBuilder getOutgoingEdgesOrBuilder(
      int index);

  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  java.util.List<com.server.graph_db.grpc.vertex.edge> 
      getIncomingEdgesList();
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  com.server.graph_db.grpc.vertex.edge getIncomingEdges(int index);
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  int getIncomingEdgesCount();
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  java.util.List<? extends com.server.graph_db.grpc.vertex.edgeOrBuilder> 
      getIncomingEdgesOrBuilderList();
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  com.server.graph_db.grpc.vertex.edgeOrBuilder getIncomingEdgesOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  boolean containsProperties(
      java.lang.String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProperties();
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */

  java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */

  java.lang.String getPropertiesOrThrow(
      java.lang.String key);
}
