// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

/**
 * Protobuf type {@code getAllVerticesIdsResponse}
 */
public final class getAllVerticesIdsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getAllVerticesIdsResponse)
    getAllVerticesIdsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getAllVerticesIdsResponse.newBuilder() to construct.
  private getAllVerticesIdsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getAllVerticesIdsResponse() {
    vertexIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new getAllVerticesIdsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getAllVerticesIdsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              vertexIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            vertexIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        vertexIds_ = vertexIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.server.graph_db.grpc.vertex.Vertex.internal_static_getAllVerticesIdsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.server.graph_db.grpc.vertex.Vertex.internal_static_getAllVerticesIdsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.class, com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.Builder.class);
  }

  public static final int VERTEXIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList vertexIds_;
  /**
   * <code>repeated string vertexIds = 1;</code>
   * @return A list containing the vertexIds.
   */
  public com.google.protobuf.ProtocolStringList
      getVertexIdsList() {
    return vertexIds_;
  }
  /**
   * <code>repeated string vertexIds = 1;</code>
   * @return The count of vertexIds.
   */
  public int getVertexIdsCount() {
    return vertexIds_.size();
  }
  /**
   * <code>repeated string vertexIds = 1;</code>
   * @param index The index of the element to return.
   * @return The vertexIds at the given index.
   */
  public java.lang.String getVertexIds(int index) {
    return vertexIds_.get(index);
  }
  /**
   * <code>repeated string vertexIds = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the vertexIds at the given index.
   */
  public com.google.protobuf.ByteString
      getVertexIdsBytes(int index) {
    return vertexIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < vertexIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vertexIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < vertexIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(vertexIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getVertexIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse)) {
      return super.equals(obj);
    }
    com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse other = (com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse) obj;

    if (!getVertexIdsList()
        .equals(other.getVertexIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVertexIdsCount() > 0) {
      hash = (37 * hash) + VERTEXIDS_FIELD_NUMBER;
      hash = (53 * hash) + getVertexIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code getAllVerticesIdsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getAllVerticesIdsResponse)
      com.server.graph_db.grpc.vertex.getAllVerticesIdsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.graph_db.grpc.vertex.Vertex.internal_static_getAllVerticesIdsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.graph_db.grpc.vertex.Vertex.internal_static_getAllVerticesIdsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.class, com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.Builder.class);
    }

    // Construct using com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      vertexIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.server.graph_db.grpc.vertex.Vertex.internal_static_getAllVerticesIdsResponse_descriptor;
    }

    @java.lang.Override
    public com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse getDefaultInstanceForType() {
      return com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse build() {
      com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse buildPartial() {
      com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse result = new com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        vertexIds_ = vertexIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.vertexIds_ = vertexIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse) {
        return mergeFrom((com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse other) {
      if (other == com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse.getDefaultInstance()) return this;
      if (!other.vertexIds_.isEmpty()) {
        if (vertexIds_.isEmpty()) {
          vertexIds_ = other.vertexIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureVertexIdsIsMutable();
          vertexIds_.addAll(other.vertexIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList vertexIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureVertexIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        vertexIds_ = new com.google.protobuf.LazyStringArrayList(vertexIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @return A list containing the vertexIds.
     */
    public com.google.protobuf.ProtocolStringList
        getVertexIdsList() {
      return vertexIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @return The count of vertexIds.
     */
    public int getVertexIdsCount() {
      return vertexIds_.size();
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @param index The index of the element to return.
     * @return The vertexIds at the given index.
     */
    public java.lang.String getVertexIds(int index) {
      return vertexIds_.get(index);
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the vertexIds at the given index.
     */
    public com.google.protobuf.ByteString
        getVertexIdsBytes(int index) {
      return vertexIds_.getByteString(index);
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @param index The index to set the value at.
     * @param value The vertexIds to set.
     * @return This builder for chaining.
     */
    public Builder setVertexIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVertexIdsIsMutable();
      vertexIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @param value The vertexIds to add.
     * @return This builder for chaining.
     */
    public Builder addVertexIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVertexIdsIsMutable();
      vertexIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @param values The vertexIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllVertexIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureVertexIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, vertexIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVertexIds() {
      vertexIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string vertexIds = 1;</code>
     * @param value The bytes of the vertexIds to add.
     * @return This builder for chaining.
     */
    public Builder addVertexIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureVertexIdsIsMutable();
      vertexIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getAllVerticesIdsResponse)
  }

  // @@protoc_insertion_point(class_scope:getAllVerticesIdsResponse)
  private static final com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse();
  }

  public static com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getAllVerticesIdsResponse>
      PARSER = new com.google.protobuf.AbstractParser<getAllVerticesIdsResponse>() {
    @java.lang.Override
    public getAllVerticesIdsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getAllVerticesIdsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getAllVerticesIdsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getAllVerticesIdsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.server.graph_db.grpc.vertex.getAllVerticesIdsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

