// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface getAllVerticesIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllVerticesIdsRequest)
    com.google.protobuf.MessageOrBuilder {
}
