// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface getVertexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getVertexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vertexId = 1;</code>
   * @return The vertexId.
   */
  java.lang.String getVertexId();
  /**
   * <code>string vertexId = 1;</code>
   * @return The bytes for vertexId.
   */
  com.google.protobuf.ByteString
      getVertexIdBytes();
}
