// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface getVertexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getVertexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 vertexId = 1;</code>
   * @return The vertexId.
   */
  int getVertexId();
}
