// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface getVerticesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getVerticesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .getVertexResponse vertices = 1;</code>
   */
  java.util.List<com.server.graph_db.grpc.vertex.getVertexResponse> 
      getVerticesList();
  /**
   * <code>repeated .getVertexResponse vertices = 1;</code>
   */
  com.server.graph_db.grpc.vertex.getVertexResponse getVertices(int index);
  /**
   * <code>repeated .getVertexResponse vertices = 1;</code>
   */
  int getVerticesCount();
  /**
   * <code>repeated .getVertexResponse vertices = 1;</code>
   */
  java.util.List<? extends com.server.graph_db.grpc.vertex.getVertexResponseOrBuilder> 
      getVerticesOrBuilderList();
  /**
   * <code>repeated .getVertexResponse vertices = 1;</code>
   */
  com.server.graph_db.grpc.vertex.getVertexResponseOrBuilder getVerticesOrBuilder(
      int index);
}
