// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

/**
 * Protobuf type {@code getVertexResponse}
 */
public final class getVertexResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getVertexResponse)
    getVertexResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getVertexResponse.newBuilder() to construct.
  private getVertexResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getVertexResponse() {
    id_ = "";
    label_ = "";
    outgoingEdges_ = java.util.Collections.emptyList();
    incomingEdges_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new getVertexResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getVertexResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            label_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              properties_ = com.google.protobuf.MapField.newMapField(
                  PropertiesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            properties__ = input.readMessage(
                PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            properties_.getMutableMap().put(
                properties__.getKey(), properties__.getValue());
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              outgoingEdges_ = new java.util.ArrayList<com.server.graph_db.grpc.vertex.edge>();
              mutable_bitField0_ |= 0x00000001;
            }
            outgoingEdges_.add(
                input.readMessage(com.server.graph_db.grpc.vertex.edge.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              incomingEdges_ = new java.util.ArrayList<com.server.graph_db.grpc.vertex.edge>();
              mutable_bitField0_ |= 0x00000002;
            }
            incomingEdges_.add(
                input.readMessage(com.server.graph_db.grpc.vertex.edge.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        outgoingEdges_ = java.util.Collections.unmodifiableList(outgoingEdges_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        incomingEdges_ = java.util.Collections.unmodifiableList(incomingEdges_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.server.graph_db.grpc.vertex.Vertex.internal_static_getVertexResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.server.graph_db.grpc.vertex.Vertex.internal_static_getVertexResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.server.graph_db.grpc.vertex.getVertexResponse.class, com.server.graph_db.grpc.vertex.getVertexResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object label_;
  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTGOINGEDGES_FIELD_NUMBER = 4;
  private java.util.List<com.server.graph_db.grpc.vertex.edge> outgoingEdges_;
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.server.graph_db.grpc.vertex.edge> getOutgoingEdgesList() {
    return outgoingEdges_;
  }
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.server.graph_db.grpc.vertex.edgeOrBuilder> 
      getOutgoingEdgesOrBuilderList() {
    return outgoingEdges_;
  }
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  @java.lang.Override
  public int getOutgoingEdgesCount() {
    return outgoingEdges_.size();
  }
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  @java.lang.Override
  public com.server.graph_db.grpc.vertex.edge getOutgoingEdges(int index) {
    return outgoingEdges_.get(index);
  }
  /**
   * <code>repeated .edge outgoingEdges = 4;</code>
   */
  @java.lang.Override
  public com.server.graph_db.grpc.vertex.edgeOrBuilder getOutgoingEdgesOrBuilder(
      int index) {
    return outgoingEdges_.get(index);
  }

  public static final int INCOMINGEDGES_FIELD_NUMBER = 5;
  private java.util.List<com.server.graph_db.grpc.vertex.edge> incomingEdges_;
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.server.graph_db.grpc.vertex.edge> getIncomingEdgesList() {
    return incomingEdges_;
  }
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.server.graph_db.grpc.vertex.edgeOrBuilder> 
      getIncomingEdgesOrBuilderList() {
    return incomingEdges_;
  }
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  @java.lang.Override
  public int getIncomingEdgesCount() {
    return incomingEdges_.size();
  }
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  @java.lang.Override
  public com.server.graph_db.grpc.vertex.edge getIncomingEdges(int index) {
    return incomingEdges_.get(index);
  }
  /**
   * <code>repeated .edge incomingEdges = 5;</code>
   */
  @java.lang.Override
  public com.server.graph_db.grpc.vertex.edgeOrBuilder getIncomingEdgesOrBuilder(
      int index) {
    return incomingEdges_.get(index);
  }

  public static final int PROPERTIES_FIELD_NUMBER = 3;
  private static final class PropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.server.graph_db.grpc.vertex.Vertex.internal_static_getVertexResponse_PropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> properties_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetProperties() {
    if (properties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PropertiesDefaultEntryHolder.defaultEntry);
    }
    return properties_;
  }

  public int getPropertiesCount() {
    return internalGetProperties().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */

  @java.lang.Override
  public boolean containsProperties(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getProperties() {
    return getPropertiesMap();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
    return internalGetProperties().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getPropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProperties(),
        PropertiesDefaultEntryHolder.defaultEntry,
        3);
    for (int i = 0; i < outgoingEdges_.size(); i++) {
      output.writeMessage(4, outgoingEdges_.get(i));
    }
    for (int i = 0; i < incomingEdges_.size(); i++) {
      output.writeMessage(5, incomingEdges_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, properties__);
    }
    for (int i = 0; i < outgoingEdges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, outgoingEdges_.get(i));
    }
    for (int i = 0; i < incomingEdges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, incomingEdges_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.server.graph_db.grpc.vertex.getVertexResponse)) {
      return super.equals(obj);
    }
    com.server.graph_db.grpc.vertex.getVertexResponse other = (com.server.graph_db.grpc.vertex.getVertexResponse) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!getOutgoingEdgesList()
        .equals(other.getOutgoingEdgesList())) return false;
    if (!getIncomingEdgesList()
        .equals(other.getIncomingEdgesList())) return false;
    if (!internalGetProperties().equals(
        other.internalGetProperties())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (getOutgoingEdgesCount() > 0) {
      hash = (37 * hash) + OUTGOINGEDGES_FIELD_NUMBER;
      hash = (53 * hash) + getOutgoingEdgesList().hashCode();
    }
    if (getIncomingEdgesCount() > 0) {
      hash = (37 * hash) + INCOMINGEDGES_FIELD_NUMBER;
      hash = (53 * hash) + getIncomingEdgesList().hashCode();
    }
    if (!internalGetProperties().getMap().isEmpty()) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProperties().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.server.graph_db.grpc.vertex.getVertexResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.server.graph_db.grpc.vertex.getVertexResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code getVertexResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getVertexResponse)
      com.server.graph_db.grpc.vertex.getVertexResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.graph_db.grpc.vertex.Vertex.internal_static_getVertexResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.graph_db.grpc.vertex.Vertex.internal_static_getVertexResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.graph_db.grpc.vertex.getVertexResponse.class, com.server.graph_db.grpc.vertex.getVertexResponse.Builder.class);
    }

    // Construct using com.server.graph_db.grpc.vertex.getVertexResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOutgoingEdgesFieldBuilder();
        getIncomingEdgesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      label_ = "";

      if (outgoingEdgesBuilder_ == null) {
        outgoingEdges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        outgoingEdgesBuilder_.clear();
      }
      if (incomingEdgesBuilder_ == null) {
        incomingEdges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        incomingEdgesBuilder_.clear();
      }
      internalGetMutableProperties().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.server.graph_db.grpc.vertex.Vertex.internal_static_getVertexResponse_descriptor;
    }

    @java.lang.Override
    public com.server.graph_db.grpc.vertex.getVertexResponse getDefaultInstanceForType() {
      return com.server.graph_db.grpc.vertex.getVertexResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.server.graph_db.grpc.vertex.getVertexResponse build() {
      com.server.graph_db.grpc.vertex.getVertexResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.server.graph_db.grpc.vertex.getVertexResponse buildPartial() {
      com.server.graph_db.grpc.vertex.getVertexResponse result = new com.server.graph_db.grpc.vertex.getVertexResponse(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.label_ = label_;
      if (outgoingEdgesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          outgoingEdges_ = java.util.Collections.unmodifiableList(outgoingEdges_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.outgoingEdges_ = outgoingEdges_;
      } else {
        result.outgoingEdges_ = outgoingEdgesBuilder_.build();
      }
      if (incomingEdgesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          incomingEdges_ = java.util.Collections.unmodifiableList(incomingEdges_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.incomingEdges_ = incomingEdges_;
      } else {
        result.incomingEdges_ = incomingEdgesBuilder_.build();
      }
      result.properties_ = internalGetProperties();
      result.properties_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.server.graph_db.grpc.vertex.getVertexResponse) {
        return mergeFrom((com.server.graph_db.grpc.vertex.getVertexResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.server.graph_db.grpc.vertex.getVertexResponse other) {
      if (other == com.server.graph_db.grpc.vertex.getVertexResponse.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      if (outgoingEdgesBuilder_ == null) {
        if (!other.outgoingEdges_.isEmpty()) {
          if (outgoingEdges_.isEmpty()) {
            outgoingEdges_ = other.outgoingEdges_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOutgoingEdgesIsMutable();
            outgoingEdges_.addAll(other.outgoingEdges_);
          }
          onChanged();
        }
      } else {
        if (!other.outgoingEdges_.isEmpty()) {
          if (outgoingEdgesBuilder_.isEmpty()) {
            outgoingEdgesBuilder_.dispose();
            outgoingEdgesBuilder_ = null;
            outgoingEdges_ = other.outgoingEdges_;
            bitField0_ = (bitField0_ & ~0x00000001);
            outgoingEdgesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOutgoingEdgesFieldBuilder() : null;
          } else {
            outgoingEdgesBuilder_.addAllMessages(other.outgoingEdges_);
          }
        }
      }
      if (incomingEdgesBuilder_ == null) {
        if (!other.incomingEdges_.isEmpty()) {
          if (incomingEdges_.isEmpty()) {
            incomingEdges_ = other.incomingEdges_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIncomingEdgesIsMutable();
            incomingEdges_.addAll(other.incomingEdges_);
          }
          onChanged();
        }
      } else {
        if (!other.incomingEdges_.isEmpty()) {
          if (incomingEdgesBuilder_.isEmpty()) {
            incomingEdgesBuilder_.dispose();
            incomingEdgesBuilder_ = null;
            incomingEdges_ = other.incomingEdges_;
            bitField0_ = (bitField0_ & ~0x00000002);
            incomingEdgesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIncomingEdgesFieldBuilder() : null;
          } else {
            incomingEdgesBuilder_.addAllMessages(other.incomingEdges_);
          }
        }
      }
      internalGetMutableProperties().mergeFrom(
          other.internalGetProperties());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.server.graph_db.grpc.vertex.getVertexResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.server.graph_db.grpc.vertex.getVertexResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>string label = 2;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.server.graph_db.grpc.vertex.edge> outgoingEdges_ =
      java.util.Collections.emptyList();
    private void ensureOutgoingEdgesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        outgoingEdges_ = new java.util.ArrayList<com.server.graph_db.grpc.vertex.edge>(outgoingEdges_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.server.graph_db.grpc.vertex.edge, com.server.graph_db.grpc.vertex.edge.Builder, com.server.graph_db.grpc.vertex.edgeOrBuilder> outgoingEdgesBuilder_;

    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public java.util.List<com.server.graph_db.grpc.vertex.edge> getOutgoingEdgesList() {
      if (outgoingEdgesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(outgoingEdges_);
      } else {
        return outgoingEdgesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public int getOutgoingEdgesCount() {
      if (outgoingEdgesBuilder_ == null) {
        return outgoingEdges_.size();
      } else {
        return outgoingEdgesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public com.server.graph_db.grpc.vertex.edge getOutgoingEdges(int index) {
      if (outgoingEdgesBuilder_ == null) {
        return outgoingEdges_.get(index);
      } else {
        return outgoingEdgesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder setOutgoingEdges(
        int index, com.server.graph_db.grpc.vertex.edge value) {
      if (outgoingEdgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.set(index, value);
        onChanged();
      } else {
        outgoingEdgesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder setOutgoingEdges(
        int index, com.server.graph_db.grpc.vertex.edge.Builder builderForValue) {
      if (outgoingEdgesBuilder_ == null) {
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.set(index, builderForValue.build());
        onChanged();
      } else {
        outgoingEdgesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder addOutgoingEdges(com.server.graph_db.grpc.vertex.edge value) {
      if (outgoingEdgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.add(value);
        onChanged();
      } else {
        outgoingEdgesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder addOutgoingEdges(
        int index, com.server.graph_db.grpc.vertex.edge value) {
      if (outgoingEdgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.add(index, value);
        onChanged();
      } else {
        outgoingEdgesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder addOutgoingEdges(
        com.server.graph_db.grpc.vertex.edge.Builder builderForValue) {
      if (outgoingEdgesBuilder_ == null) {
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.add(builderForValue.build());
        onChanged();
      } else {
        outgoingEdgesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder addOutgoingEdges(
        int index, com.server.graph_db.grpc.vertex.edge.Builder builderForValue) {
      if (outgoingEdgesBuilder_ == null) {
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.add(index, builderForValue.build());
        onChanged();
      } else {
        outgoingEdgesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder addAllOutgoingEdges(
        java.lang.Iterable<? extends com.server.graph_db.grpc.vertex.edge> values) {
      if (outgoingEdgesBuilder_ == null) {
        ensureOutgoingEdgesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outgoingEdges_);
        onChanged();
      } else {
        outgoingEdgesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder clearOutgoingEdges() {
      if (outgoingEdgesBuilder_ == null) {
        outgoingEdges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        outgoingEdgesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public Builder removeOutgoingEdges(int index) {
      if (outgoingEdgesBuilder_ == null) {
        ensureOutgoingEdgesIsMutable();
        outgoingEdges_.remove(index);
        onChanged();
      } else {
        outgoingEdgesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public com.server.graph_db.grpc.vertex.edge.Builder getOutgoingEdgesBuilder(
        int index) {
      return getOutgoingEdgesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public com.server.graph_db.grpc.vertex.edgeOrBuilder getOutgoingEdgesOrBuilder(
        int index) {
      if (outgoingEdgesBuilder_ == null) {
        return outgoingEdges_.get(index);  } else {
        return outgoingEdgesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public java.util.List<? extends com.server.graph_db.grpc.vertex.edgeOrBuilder> 
         getOutgoingEdgesOrBuilderList() {
      if (outgoingEdgesBuilder_ != null) {
        return outgoingEdgesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(outgoingEdges_);
      }
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public com.server.graph_db.grpc.vertex.edge.Builder addOutgoingEdgesBuilder() {
      return getOutgoingEdgesFieldBuilder().addBuilder(
          com.server.graph_db.grpc.vertex.edge.getDefaultInstance());
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public com.server.graph_db.grpc.vertex.edge.Builder addOutgoingEdgesBuilder(
        int index) {
      return getOutgoingEdgesFieldBuilder().addBuilder(
          index, com.server.graph_db.grpc.vertex.edge.getDefaultInstance());
    }
    /**
     * <code>repeated .edge outgoingEdges = 4;</code>
     */
    public java.util.List<com.server.graph_db.grpc.vertex.edge.Builder> 
         getOutgoingEdgesBuilderList() {
      return getOutgoingEdgesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.server.graph_db.grpc.vertex.edge, com.server.graph_db.grpc.vertex.edge.Builder, com.server.graph_db.grpc.vertex.edgeOrBuilder> 
        getOutgoingEdgesFieldBuilder() {
      if (outgoingEdgesBuilder_ == null) {
        outgoingEdgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.server.graph_db.grpc.vertex.edge, com.server.graph_db.grpc.vertex.edge.Builder, com.server.graph_db.grpc.vertex.edgeOrBuilder>(
                outgoingEdges_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        outgoingEdges_ = null;
      }
      return outgoingEdgesBuilder_;
    }

    private java.util.List<com.server.graph_db.grpc.vertex.edge> incomingEdges_ =
      java.util.Collections.emptyList();
    private void ensureIncomingEdgesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        incomingEdges_ = new java.util.ArrayList<com.server.graph_db.grpc.vertex.edge>(incomingEdges_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.server.graph_db.grpc.vertex.edge, com.server.graph_db.grpc.vertex.edge.Builder, com.server.graph_db.grpc.vertex.edgeOrBuilder> incomingEdgesBuilder_;

    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public java.util.List<com.server.graph_db.grpc.vertex.edge> getIncomingEdgesList() {
      if (incomingEdgesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(incomingEdges_);
      } else {
        return incomingEdgesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public int getIncomingEdgesCount() {
      if (incomingEdgesBuilder_ == null) {
        return incomingEdges_.size();
      } else {
        return incomingEdgesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public com.server.graph_db.grpc.vertex.edge getIncomingEdges(int index) {
      if (incomingEdgesBuilder_ == null) {
        return incomingEdges_.get(index);
      } else {
        return incomingEdgesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder setIncomingEdges(
        int index, com.server.graph_db.grpc.vertex.edge value) {
      if (incomingEdgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncomingEdgesIsMutable();
        incomingEdges_.set(index, value);
        onChanged();
      } else {
        incomingEdgesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder setIncomingEdges(
        int index, com.server.graph_db.grpc.vertex.edge.Builder builderForValue) {
      if (incomingEdgesBuilder_ == null) {
        ensureIncomingEdgesIsMutable();
        incomingEdges_.set(index, builderForValue.build());
        onChanged();
      } else {
        incomingEdgesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder addIncomingEdges(com.server.graph_db.grpc.vertex.edge value) {
      if (incomingEdgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncomingEdgesIsMutable();
        incomingEdges_.add(value);
        onChanged();
      } else {
        incomingEdgesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder addIncomingEdges(
        int index, com.server.graph_db.grpc.vertex.edge value) {
      if (incomingEdgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncomingEdgesIsMutable();
        incomingEdges_.add(index, value);
        onChanged();
      } else {
        incomingEdgesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder addIncomingEdges(
        com.server.graph_db.grpc.vertex.edge.Builder builderForValue) {
      if (incomingEdgesBuilder_ == null) {
        ensureIncomingEdgesIsMutable();
        incomingEdges_.add(builderForValue.build());
        onChanged();
      } else {
        incomingEdgesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder addIncomingEdges(
        int index, com.server.graph_db.grpc.vertex.edge.Builder builderForValue) {
      if (incomingEdgesBuilder_ == null) {
        ensureIncomingEdgesIsMutable();
        incomingEdges_.add(index, builderForValue.build());
        onChanged();
      } else {
        incomingEdgesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder addAllIncomingEdges(
        java.lang.Iterable<? extends com.server.graph_db.grpc.vertex.edge> values) {
      if (incomingEdgesBuilder_ == null) {
        ensureIncomingEdgesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, incomingEdges_);
        onChanged();
      } else {
        incomingEdgesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder clearIncomingEdges() {
      if (incomingEdgesBuilder_ == null) {
        incomingEdges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        incomingEdgesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public Builder removeIncomingEdges(int index) {
      if (incomingEdgesBuilder_ == null) {
        ensureIncomingEdgesIsMutable();
        incomingEdges_.remove(index);
        onChanged();
      } else {
        incomingEdgesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public com.server.graph_db.grpc.vertex.edge.Builder getIncomingEdgesBuilder(
        int index) {
      return getIncomingEdgesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public com.server.graph_db.grpc.vertex.edgeOrBuilder getIncomingEdgesOrBuilder(
        int index) {
      if (incomingEdgesBuilder_ == null) {
        return incomingEdges_.get(index);  } else {
        return incomingEdgesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public java.util.List<? extends com.server.graph_db.grpc.vertex.edgeOrBuilder> 
         getIncomingEdgesOrBuilderList() {
      if (incomingEdgesBuilder_ != null) {
        return incomingEdgesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(incomingEdges_);
      }
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public com.server.graph_db.grpc.vertex.edge.Builder addIncomingEdgesBuilder() {
      return getIncomingEdgesFieldBuilder().addBuilder(
          com.server.graph_db.grpc.vertex.edge.getDefaultInstance());
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public com.server.graph_db.grpc.vertex.edge.Builder addIncomingEdgesBuilder(
        int index) {
      return getIncomingEdgesFieldBuilder().addBuilder(
          index, com.server.graph_db.grpc.vertex.edge.getDefaultInstance());
    }
    /**
     * <code>repeated .edge incomingEdges = 5;</code>
     */
    public java.util.List<com.server.graph_db.grpc.vertex.edge.Builder> 
         getIncomingEdgesBuilderList() {
      return getIncomingEdgesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.server.graph_db.grpc.vertex.edge, com.server.graph_db.grpc.vertex.edge.Builder, com.server.graph_db.grpc.vertex.edgeOrBuilder> 
        getIncomingEdgesFieldBuilder() {
      if (incomingEdgesBuilder_ == null) {
        incomingEdgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.server.graph_db.grpc.vertex.edge, com.server.graph_db.grpc.vertex.edge.Builder, com.server.graph_db.grpc.vertex.edgeOrBuilder>(
                incomingEdges_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        incomingEdges_ = null;
      }
      return incomingEdgesBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableProperties() {
      onChanged();;
      if (properties_ == null) {
        properties_ = com.google.protobuf.MapField.newMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!properties_.isMutable()) {
        properties_ = properties_.copy();
      }
      return properties_;
    }

    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    @java.lang.Override
    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearProperties() {
      internalGetMutableProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public Builder removeProperties(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableProperties() {
      return internalGetMutableProperties().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    public Builder putProperties(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProperties().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public Builder putAllProperties(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableProperties().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getVertexResponse)
  }

  // @@protoc_insertion_point(class_scope:getVertexResponse)
  private static final com.server.graph_db.grpc.vertex.getVertexResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.server.graph_db.grpc.vertex.getVertexResponse();
  }

  public static com.server.graph_db.grpc.vertex.getVertexResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getVertexResponse>
      PARSER = new com.google.protobuf.AbstractParser<getVertexResponse>() {
    @java.lang.Override
    public getVertexResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getVertexResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getVertexResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getVertexResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.server.graph_db.grpc.vertex.getVertexResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

