// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public interface updateEdgeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updateEdgeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sourceVertexId = 1;</code>
   * @return The sourceVertexId.
   */
  java.lang.String getSourceVertexId();
  /**
   * <code>string sourceVertexId = 1;</code>
   * @return The bytes for sourceVertexId.
   */
  com.google.protobuf.ByteString
      getSourceVertexIdBytes();

  /**
   * <code>string destinationVertexId = 2;</code>
   * @return The destinationVertexId.
   */
  java.lang.String getDestinationVertexId();
  /**
   * <code>string destinationVertexId = 2;</code>
   * @return The bytes for destinationVertexId.
   */
  com.google.protobuf.ByteString
      getDestinationVertexIdBytes();

  /**
   * <code>string label = 3;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 3;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  boolean containsProperties(
      java.lang.String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProperties();
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */

  java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */

  java.lang.String getPropertiesOrThrow(
      java.lang.String key);

  /**
   * <code>bool isOutGoing = 5;</code>
   * @return The isOutGoing.
   */
  boolean getIsOutGoing();
}
