// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public final class Vertex {
  private Vertex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAllVerticesIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAllVerticesIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAllVerticesIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAllVerticesIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getEdgesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getEdgesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getEdgesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getEdgesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getOutGoingEdgesForVerticesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getOutGoingEdgesForVerticesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getIncomingEdgesForVerticesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getIncomingEdgesForVerticesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getOutgoingEdgesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getOutgoingEdgesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getIncomingEdgesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getIncomingEdgesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getOutgoingEdgesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getOutgoingEdgesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getIncomingEdgesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getIncomingEdgesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_createEdgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_createEdgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_createEdgeRequest_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_createEdgeRequest_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteEdgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteEdgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateEdgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateEdgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateEdgeRequest_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateEdgeRequest_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_createEdgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_createEdgeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteEdgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteEdgeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateEdgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateEdgeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVertexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVertexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVerticesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVerticesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_createVertexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_createVertexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_createVertexRequest_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_createVertexRequest_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteVertexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteVertexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateVertexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateVertexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateVertexRequest_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateVertexRequest_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_createVertexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_createVertexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteVertexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteVertexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateVertexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateVertexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVertexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVertexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVertexResponse_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVertexResponse_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVerticesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVerticesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edge_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edge_PropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014vertex.proto\032\017traverser.proto\"\032\n\030getAl" +
      "lVerticesIdsRequest\".\n\031getAllVerticesIds" +
      "Response\022\021\n\tvertexIds\030\001 \003(\t\"+\n\017getEdgesR" +
      "equest\022\030\n\007edgeIds\030\001 \003(\0132\007.edgeId\"(\n\020getE" +
      "dgesResponse\022\024\n\005edges\030\001 \003(\0132\005.edge\"7\n\"ge" +
      "tOutGoingEdgesForVerticesRequest\022\021\n\tvert" +
      "exIds\030\001 \003(\t\"7\n\"getIncomingEdgesForVertic" +
      "esRequest\022\021\n\tvertexIds\030\001 \003(\t\"+\n\027getOutgo" +
      "ingEdgesRequest\022\020\n\010vertexId\030\001 \001(\t\"+\n\027get" +
      "IncomingEdgesRequest\022\020\n\010vertexId\030\001 \001(\t\"0" +
      "\n\030getOutgoingEdgesResponse\022\024\n\005edges\030\001 \003(" +
      "\0132\005.edge\"0\n\030getIncomingEdgesResponse\022\024\n\005" +
      "edges\030\001 \003(\0132\005.edge\"\326\001\n\021createEdgeRequest" +
      "\022\026\n\016sourceVertexId\030\001 \001(\t\022\033\n\023destinationV" +
      "ertexId\030\002 \001(\t\022\r\n\005label\030\003 \001(\t\0226\n\nproperti" +
      "es\030\004 \003(\0132\".createEdgeRequest.PropertiesE" +
      "ntry\022\022\n\nisOutGoing\030\005 \001(\010\0321\n\017PropertiesEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"k\n\021d" +
      "eleteEdgeRequest\022\026\n\016sourceVertexId\030\001 \001(\t" +
      "\022\033\n\023destinationVertexId\030\002 \001(\t\022\r\n\005label\030\003" +
      " \001(\t\022\022\n\nisOutGoing\030\004 \001(\010\"\326\001\n\021updateEdgeR" +
      "equest\022\026\n\016sourceVertexId\030\001 \001(\t\022\033\n\023destin" +
      "ationVertexId\030\002 \001(\t\022\r\n\005label\030\003 \001(\t\0226\n\npr" +
      "operties\030\004 \003(\0132\".updateEdgeRequest.Prope" +
      "rtiesEntry\022\022\n\nisOutGoing\030\005 \001(\010\0321\n\017Proper" +
      "tiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"6\n\022createEdgeResponse\022\017\n\007success\030\001 \001(\010" +
      "\022\017\n\007message\030\002 \001(\t\"6\n\022deleteEdgeResponse\022" +
      "\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"6\n\022upd" +
      "ateEdgeResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007mess" +
      "age\030\002 \001(\t\"$\n\020getVertexRequest\022\020\n\010vertexI" +
      "d\030\001 \001(\t\"\'\n\022getVerticesRequest\022\021\n\tvertexI" +
      "ds\030\001 \003(\t\"\235\001\n\023createVertexRequest\022\n\n\002id\030\001" +
      " \001(\t\022\r\n\005label\030\002 \001(\t\0228\n\nproperties\030\003 \003(\0132" +
      "$.createVertexRequest.PropertiesEntry\0321\n" +
      "\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"\'\n\023deleteVertexRequest\022\020\n\010verte" +
      "xId\030\001 \001(\t\"\235\001\n\023updateVertexRequest\022\n\n\002id\030" +
      "\001 \001(\t\022\r\n\005label\030\002 \001(\t\0228\n\nproperties\030\003 \003(\013" +
      "2$.updateVertexRequest.PropertiesEntry\0321" +
      "\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"8\n\024createVertexResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"8\n\024deleteVer" +
      "texResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030" +
      "\002 \001(\t\"8\n\024updateVertexResponse\022\017\n\007success" +
      "\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\231\001\n\021getVertexRes" +
      "ponse\022\n\n\002id\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\0226\n\nprop" +
      "erties\030\003 \003(\0132\".getVertexResponse.Propert" +
      "iesEntry\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\";\n\023getVerticesRespon" +
      "se\022$\n\010vertices\030\001 \003(\0132\022.getVertexResponse" +
      "\"\250\001\n\004edge\022\033\n\023destinationVertexId\030\001 \001(\t\022\026" +
      "\n\016sourceVertexId\030\002 \001(\t\022\r\n\005label\030\003 \001(\t\022)\n" +
      "\nproperties\030\004 \003(\0132\025.edge.PropertiesEntry" +
      "\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\0012\262\007\n\rVertexService\0224\n\tgetVert" +
      "ex\022\021.getVertexRequest\032\022.getVertexRespons" +
      "e\"\000\022:\n\013getVertices\022\023.getVerticesRequest\032" +
      "\024.getVerticesResponse\"\000\022=\n\014createVertex\022" +
      "\024.createVertexRequest\032\025.createVertexResp" +
      "onse\"\000\022=\n\014deleteVertex\022\024.deleteVertexReq" +
      "uest\032\025.deleteVertexResponse\"\000\022=\n\014updateV" +
      "ertex\022\024.updateVertexRequest\032\025.updateVert" +
      "exResponse\"\000\0227\n\ncreateEdge\022\022.createEdgeR" +
      "equest\032\023.createEdgeResponse\"\000\0227\n\ndeleteE" +
      "dge\022\022.deleteEdgeRequest\032\023.deleteEdgeResp" +
      "onse\"\000\0227\n\nupdateEdge\022\022.updateEdgeRequest" +
      "\032\023.updateEdgeResponse\"\000\022I\n\020getOutgoingEd" +
      "ges\022\030.getOutgoingEdgesRequest\032\031.getOutgo" +
      "ingEdgesResponse\"\000\022I\n\020getIncomingEdges\022\030" +
      ".getIncomingEdgesRequest\032\031.getIncomingEd" +
      "gesResponse\"\000\0221\n\010getEdges\022\020.getEdgesRequ" +
      "est\032\021.getEdgesResponse\"\000\022W\n\033getOutgoingE" +
      "dgesForVertices\022#.getOutGoingEdgesForVer" +
      "ticesRequest\032\021.getEdgesResponse\"\000\022W\n\033get" +
      "IncomingEdgesForVertices\022#.getIncomingEd" +
      "gesForVerticesRequest\032\021.getEdgesResponse" +
      "\"\000\022L\n\021getAllVerticesIds\022\031.getAllVertices" +
      "IdsRequest\032\032.getAllVerticesIdsResponse\"\000" +
      "B#\n\037com.server.graph_db.grpc.vertexP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.server.graph_db.grpc.traverser.Traverser.getDescriptor(),
        });
    internal_static_getAllVerticesIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getAllVerticesIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAllVerticesIdsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_getAllVerticesIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getAllVerticesIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAllVerticesIdsResponse_descriptor,
        new java.lang.String[] { "VertexIds", });
    internal_static_getEdgesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_getEdgesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getEdgesRequest_descriptor,
        new java.lang.String[] { "EdgeIds", });
    internal_static_getEdgesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_getEdgesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getEdgesResponse_descriptor,
        new java.lang.String[] { "Edges", });
    internal_static_getOutGoingEdgesForVerticesRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_getOutGoingEdgesForVerticesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getOutGoingEdgesForVerticesRequest_descriptor,
        new java.lang.String[] { "VertexIds", });
    internal_static_getIncomingEdgesForVerticesRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_getIncomingEdgesForVerticesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getIncomingEdgesForVerticesRequest_descriptor,
        new java.lang.String[] { "VertexIds", });
    internal_static_getOutgoingEdgesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_getOutgoingEdgesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getOutgoingEdgesRequest_descriptor,
        new java.lang.String[] { "VertexId", });
    internal_static_getIncomingEdgesRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_getIncomingEdgesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getIncomingEdgesRequest_descriptor,
        new java.lang.String[] { "VertexId", });
    internal_static_getOutgoingEdgesResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_getOutgoingEdgesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getOutgoingEdgesResponse_descriptor,
        new java.lang.String[] { "Edges", });
    internal_static_getIncomingEdgesResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_getIncomingEdgesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getIncomingEdgesResponse_descriptor,
        new java.lang.String[] { "Edges", });
    internal_static_createEdgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_createEdgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_createEdgeRequest_descriptor,
        new java.lang.String[] { "SourceVertexId", "DestinationVertexId", "Label", "Properties", "IsOutGoing", });
    internal_static_createEdgeRequest_PropertiesEntry_descriptor =
      internal_static_createEdgeRequest_descriptor.getNestedTypes().get(0);
    internal_static_createEdgeRequest_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_createEdgeRequest_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_deleteEdgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_deleteEdgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteEdgeRequest_descriptor,
        new java.lang.String[] { "SourceVertexId", "DestinationVertexId", "Label", "IsOutGoing", });
    internal_static_updateEdgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_updateEdgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateEdgeRequest_descriptor,
        new java.lang.String[] { "SourceVertexId", "DestinationVertexId", "Label", "Properties", "IsOutGoing", });
    internal_static_updateEdgeRequest_PropertiesEntry_descriptor =
      internal_static_updateEdgeRequest_descriptor.getNestedTypes().get(0);
    internal_static_updateEdgeRequest_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateEdgeRequest_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_createEdgeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_createEdgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_createEdgeResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_deleteEdgeResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_deleteEdgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteEdgeResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_updateEdgeResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_updateEdgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateEdgeResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_getVertexRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_getVertexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVertexRequest_descriptor,
        new java.lang.String[] { "VertexId", });
    internal_static_getVerticesRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_getVerticesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVerticesRequest_descriptor,
        new java.lang.String[] { "VertexIds", });
    internal_static_createVertexRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_createVertexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_createVertexRequest_descriptor,
        new java.lang.String[] { "Id", "Label", "Properties", });
    internal_static_createVertexRequest_PropertiesEntry_descriptor =
      internal_static_createVertexRequest_descriptor.getNestedTypes().get(0);
    internal_static_createVertexRequest_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_createVertexRequest_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_deleteVertexRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_deleteVertexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteVertexRequest_descriptor,
        new java.lang.String[] { "VertexId", });
    internal_static_updateVertexRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_updateVertexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateVertexRequest_descriptor,
        new java.lang.String[] { "Id", "Label", "Properties", });
    internal_static_updateVertexRequest_PropertiesEntry_descriptor =
      internal_static_updateVertexRequest_descriptor.getNestedTypes().get(0);
    internal_static_updateVertexRequest_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateVertexRequest_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_createVertexResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_createVertexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_createVertexResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_deleteVertexResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_deleteVertexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteVertexResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_updateVertexResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_updateVertexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateVertexResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_getVertexResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_getVertexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVertexResponse_descriptor,
        new java.lang.String[] { "Id", "Label", "Properties", });
    internal_static_getVertexResponse_PropertiesEntry_descriptor =
      internal_static_getVertexResponse_descriptor.getNestedTypes().get(0);
    internal_static_getVertexResponse_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVertexResponse_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_getVerticesResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_getVerticesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVerticesResponse_descriptor,
        new java.lang.String[] { "Vertices", });
    internal_static_edge_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edge_descriptor,
        new java.lang.String[] { "DestinationVertexId", "SourceVertexId", "Label", "Properties", });
    internal_static_edge_PropertiesEntry_descriptor =
      internal_static_edge_descriptor.getNestedTypes().get(0);
    internal_static_edge_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edge_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.server.graph_db.grpc.traverser.Traverser.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
