// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vertex.proto

package com.server.graph_db.grpc.vertex;

public final class Vertex {
  private Vertex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVertexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVertexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVerticesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVerticesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVertexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVertexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVertexResponse_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVertexResponse_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getVerticesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getVerticesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edge_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edge_PropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014vertex.proto\"$\n\020getVertexRequest\022\020\n\010ve" +
      "rtexId\030\001 \001(\t\"\'\n\022getVerticesRequest\022\021\n\tve" +
      "rtexIds\030\001 \003(\t\"\325\001\n\021getVertexResponse\022\n\n\002i" +
      "d\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\022\034\n\routgoingEdges\030" +
      "\004 \003(\0132\005.edge\022\034\n\rincomingEdges\030\005 \003(\0132\005.ed" +
      "ge\0226\n\nproperties\030\003 \003(\0132\".getVertexRespon" +
      "se.PropertiesEntry\0321\n\017PropertiesEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\";\n\023getVert" +
      "icesResponse\022$\n\010vertices\030\001 \003(\0132\022.getVert" +
      "exResponse\"\220\001\n\004edge\022\033\n\023destinationVertex" +
      "Id\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\022)\n\nproperties\030\003 " +
      "\003(\0132\025.edge.PropertiesEntry\0321\n\017Properties" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012\201\001" +
      "\n\rVertexService\0224\n\tgetVertex\022\021.getVertex" +
      "Request\032\022.getVertexResponse\"\000\022:\n\013getVert" +
      "ices\022\023.getVerticesRequest\032\024.getVerticesR" +
      "esponse\"\000B#\n\037com.server.graph_db.grpc.ve" +
      "rtexP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_getVertexRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getVertexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVertexRequest_descriptor,
        new java.lang.String[] { "VertexId", });
    internal_static_getVerticesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getVerticesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVerticesRequest_descriptor,
        new java.lang.String[] { "VertexIds", });
    internal_static_getVertexResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_getVertexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVertexResponse_descriptor,
        new java.lang.String[] { "Id", "Label", "OutgoingEdges", "IncomingEdges", "Properties", });
    internal_static_getVertexResponse_PropertiesEntry_descriptor =
      internal_static_getVertexResponse_descriptor.getNestedTypes().get(0);
    internal_static_getVertexResponse_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVertexResponse_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_getVerticesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_getVerticesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getVerticesResponse_descriptor,
        new java.lang.String[] { "Vertices", });
    internal_static_edge_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edge_descriptor,
        new java.lang.String[] { "DestinationVertexId", "Label", "Properties", });
    internal_static_edge_PropertiesEntry_descriptor =
      internal_static_edge_descriptor.getNestedTypes().get(0);
    internal_static_edge_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edge_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
